version: '3'

services:
  webserver:
    image: nginx:1.17.9-alpine
    container_name: exambuddy-static
    restart: unless-stopped
    expose:
      - 80
    labels:
      traefik.enable: true
      traefik.http.routers.exambuddy-http.rule: Host(`exambuddy.co.uk`,`www.exambuddy.co.uk`)
      traefik.http.routers.exambuddy-http.entrypoints: web
      traefik.http.routers.exambuddy.rule: Host(`exambuddy.co.uk`)
      traefik.http.routers.exambuddy.entrypoints: websecure
      traefik.http.routers.exambuddy.tls.certresolver: letsencrypt
      traefik.http.routers.exambuddy-http.middlewares: https_redirect@file
      traefik.http.routers.exambuddy-http.middlewares: wwwtohttps@file
    volumes:
      - ./html:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d

networks:
  default:
    external:
      name: traefik-proxy
